### ISSUE TITLE
Directory service phase 1

### ISSUE THREAD

**Issue by Jibinxavier** [Jibinxavier/DistributedSystems#12]
The initial plan is to build the basic blocks with monitoring and some degree of failure tolerance.

- [x] build service discovery infrastructure using consul and docker (health checks)
- [ ] 3 Copies of directory service; all registered to service discovery; whoever initialises first will be the leader
- [ ] ~ Store the metadata such as the file server number, file server leader ~
